version: '3.8'

services:

    mongo:
        image: mongo:latest
        container_name: mongo
        environment:
            MONGO_INITDB_DATABASE: mongo
        ports:
            - "27017:27017"
        volumes:
            - ./volumes/mongo_data:/data/db
